
import { Character, CharacterRarity, ElementType, BaseSkill, Currency, StatusEffectType, ComputedCharacterStats } from '../types';

export const MAX_CHARACTER_LEVEL_BY_STARS: Record<number, number> = {
  1: 30, 2: 40, 3: 50, 4: 60, 5: 70, 6: 80, 7: 90,
};

export const SHARDS_PER_STAR: Record<number, number> = {
  2: 20, 3: 50, 4: 100, 5: 150, 6: 200, 7: 300,
};

export const STAT_BONUS_PER_STAR: Record<number, number> = { // Percentage increase
  1: 0, 2: 10, 3: 15, 4: 20, 5: 25, 6: 30, 7: 40,
};

const SKILL_UPGRADE_COST_GOLD_BASE = 1000;
const SKILL_UPGRADE_COST_BOOK_NORMAL_BASE = 5;
const SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE = 1;
const HIDDEN_HERO_SKILL_COST_GOLD = 500000;
const HIDDEN_HERO_SKILL_COST_BOOK = 25;


export const BASE_SKILLS_DATA: Record<string, Omit<BaseSkill, 'id'>> = {
  defaultAttack: { name: '普通攻擊', description: '對單體敵人造成100%攻擊力的傷害。', damageMultiplier: 1, emoji: '⚔️', maxLevel: 10, upgradeCost: (l) => ({ [Currency.GOLD]: 100*l}), upgradeEffect: (l) => ({ damageMultiplier: 1 + (l-1)*0.05 }) },
  s001_water_single: { name: '水流斬', description: '對單體敵人造成120%攻擊力的水屬性傷害。', damageMultiplier: 1.2, emoji: '💧', maxLevel: 5, upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * l, [Currency.SKILL_BOOK_NORMAL]: SKILL_UPGRADE_COST_BOOK_NORMAL_BASE * l }), upgradeEffect: (l) => ({damageMultiplier: 1.2 + (l-1)*0.15})},
  s002_water_heal: { name: '治療波', description: '回復我方單體生命值最低角色50%攻擊力的生命。', healMultiplier: 0.5, target: 'ally_single_lowest_hp', cooldown: 3, emoji: '💖', maxLevel: 5, upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * l, [Currency.SKILL_BOOK_NORMAL]: SKILL_UPGRADE_COST_BOOK_NORMAL_BASE * l }), upgradeEffect: (l) => ({healMultiplier: 0.5 + (l-1)*0.1})},
  s003_fire_single: { name: '火焰衝撞', description: '對單體敵人造成130%攻擊力的火屬性傷害。', damageMultiplier: 1.3, emoji: '🔥', maxLevel: 5, upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * l, [Currency.SKILL_BOOK_NORMAL]: SKILL_UPGRADE_COST_BOOK_NORMAL_BASE * l }), upgradeEffect: (l) => ({damageMultiplier: 1.3 + (l-1)*0.18})},
  s004_fire_buff: { name: '燃燒意志', description: '提升自身20%攻擊力，持續2回合。', cooldown: 4, emoji: '💪', maxLevel: 3, upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 1.5 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * l }), 
    buffs: [{ stat: 'attack_increase', value: 20, duration: 2, targetType: 'self' }], 
    upgradeEffect: (l) => ({ buffs: [{ stat: 'attack_increase', value: 20 + (l-1)*5, duration: 2 + Math.floor((l-1)/2), targetType: 'self' }] })
  },
  s005_wind_aoe: { name: '風刃', description: '對敵方全體造成80%攻擊力的風屬性傷害。', damageMultiplier: 0.8, target: 'enemy_all', emoji: '🍃', maxLevel: 5, upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * l, [Currency.SKILL_BOOK_NORMAL]: SKILL_UPGRADE_COST_BOOK_NORMAL_BASE * l }), upgradeEffect: (l) => ({damageMultiplier: 0.8 + (l-1)*0.1})},
  s006_wind_buff: { name: '疾風步', description: '提升自身30%速度，持續2回合。', cooldown: 3, emoji: '💨', maxLevel: 3, upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 1.5 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * l }), 
    buffs: [{ stat: 'speed_increase', value: 30, duration: 2, targetType: 'self' }], 
    upgradeEffect: (l) => ({ buffs: [{ stat: 'speed_increase', value: 30 + (l-1)*10, duration: 2 + Math.floor((l-1)/2), targetType: 'self' }] })
  },
  s007_thunder_single_stun: { name: '雷霆萬鈞', description: '對單體敵人造成200%攻擊力的雷屬性傷害，並有30%機率使其無法行動1回合。', damageMultiplier: 2.0, emoji: '⚡', maxLevel: 5, applyStatusEffects: [{type: StatusEffectType.UNABLE_TO_ACT, chance: 0.3, duration: 1}], upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 2 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * (l+1) }), upgradeEffect: (l) => ({damageMultiplier: 2.0 + (l-1)*0.25, applyStatusEffects: [{ type: StatusEffectType.UNABLE_TO_ACT, chance: 0.3 + (l-1)*0.05, duration: 1 }]})},
  s008_thunder_multi: { name: '電光石火', description: '對敵方隨機3個目標造成100%攻擊力的雷屬性傷害。', damageMultiplier: 1.0, cooldown: 2, emoji: '✨', maxLevel: 5, target: 'random_enemy_targets', numRandomTargets: 3, upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 1.5 * l, [Currency.SKILL_BOOK_NORMAL]: SKILL_UPGRADE_COST_BOOK_NORMAL_BASE * (l+1) }), upgradeEffect: (l) => ({damageMultiplier: 1.0 + (l-1)*0.12})},
  s009_ur_water_aoe_debuff: { name: '海神之怒', description: '對敵方全體造成150%攻擊力的水屬性傷害，並降低其15%防禦力，持續2回合。', damageMultiplier: 1.5, target: 'enemy_all', emoji: '🌊', maxLevel: 5, debuffs: [{stat: 'defense_reduction', value: 15, duration: 2, chance: 1, targetType: 'all_enemies'}], upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 3 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * (l+2) }), upgradeEffect: (l) => ({damageMultiplier: 1.5 + (l-1)*0.2, debuffs: [{stat: 'defense_reduction', value: 15 + (l-1)*5, duration: 2, chance: 1, targetType: 'all_enemies'}]})},
  s010_ur_water_team_heal_shield: { name: '深海祝福', description: '我方全體回復100%攻擊力的生命值。', healMultiplier: 1.0, target: 'ally_all', cooldown: 5, emoji: '🛡️', maxLevel: 3, upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 5 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * (l*2) }), upgradeEffect: (l) => ({healMultiplier: 1.0 + (l-1)*0.25})},
  s011_ssr_fire_aoe_dot: { name: '煉獄爆破', description: '對敵方全體造成160%攻擊力的火屬性傷害，附加30%傷害DOT3回合。', damageMultiplier: 1.6, target: 'enemy_all', emoji: '💥', maxLevel: 5, applyStatusEffects: [{type: StatusEffectType.DAMAGE_OVER_TIME, dotDamageMultiplier: 0.3, duration: 3, chance: 1}], upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 2.5 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * (l+1) }), upgradeEffect: (l) => ({damageMultiplier: 1.6 + (l-1)*0.2, applyStatusEffects: [{type: StatusEffectType.DAMAGE_OVER_TIME, dotDamageMultiplier: 0.3 + (l-1)*0.05, duration: 3, chance: 1}]})},
  s012_ssr_fire_passive_buff: { name: '不屈戰魂', description: '自身生命低於30%時，攻擊力提升50%。(被動)', emoji: '🔥', maxLevel: 1, isPassive: true, buffs: [{stat:'attack_increase', value: 50, duration: 99, targetType:'self' /* condition handled in battle logic */ }], upgradeCost: (l) => ({}), upgradeEffect: (l) => ({}) },
  s013_light_protect: { name: '聖光守護', description: '全隊防禦提升50%，持續2回合。', cooldown: 4, emoji: '✨', maxLevel: 3, buffs: [{stat: 'defense_increase', value: 50, duration: 2, targetType: 'all_allies'}], upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 2 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * (l+1) }), upgradeEffect: (l) => ({buffs: [{stat: 'defense_increase', value: 50 + (l-1)*10, duration: 2 + Math.floor((l-1)/2), targetType: 'all_allies'}]})},
  s014_dark_sacrifice: { name: '暗影獻祭', description: '對敵方單體造成300%攻擊力的暗屬性傷害，自身損失10%當前生命。', damageMultiplier: 3.0, emoji: '💀', maxLevel: 5, specialConditions: [{type: 'self_damage_current_hp_perc', selfDamagePercent: 0.1}], upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 2.5 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * (l+2) }), upgradeEffect: (l) => ({damageMultiplier: 3.0 + (l-1)*0.3})},
  s015_ur_light_revive: { name: '光之奇蹟', description: '回復全隊30%的生命值。', healMultiplier: 0.3, target: 'ally_all', cooldown: 6, emoji: '🌟', maxLevel: 3, upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 6 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * (l*3) }), upgradeEffect: (l) => ({healMultiplier: 0.3 + (l-1)*0.1})},
  s016_dark_sr_dot: { name: '腐蝕暗流', description: '對敵方單體造成90%攻擊力的暗屬性傷害，並附加30%傷害的DOT3回合。', damageMultiplier: 0.9, cooldown: 2, emoji: '☠️', maxLevel: 5, applyStatusEffects: [{type: StatusEffectType.DAMAGE_OVER_TIME, dotDamageMultiplier: 0.3, duration: 3, chance: 1}], upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 1.2 * l, [Currency.SKILL_BOOK_NORMAL]: SKILL_UPGRADE_COST_BOOK_NORMAL_BASE * (l+1) }), upgradeEffect: (l) => ({damageMultiplier: 0.9 + (l-1)*0.1, applyStatusEffects: [{type: StatusEffectType.DAMAGE_OVER_TIME, dotDamageMultiplier: 0.3 + (l-1)*0.05, duration: 3, chance: 1}] }) },
  s017_light_ssr_shield_reflect: { name: '星光壁壘', description: '為我方全體施加等同自身攻擊力150%的護盾，持續2回合。', shieldMultiplier: 1.5, target: 'ally_all', cooldown: 4, emoji: '🛡️', maxLevel: 5, upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 3 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * (l+2) }), upgradeEffect: (l) => ({shieldMultiplier: 1.5 + (l-1)*0.2, buffs: [{stat: 'defense_increase', value: (l-1)*5, duration:2, targetType:'all_allies'}]}) },
  s018_ur_wind_single_execute: { name: '終末風暴', description: '對單體敵人造成250%攻擊力的風屬性傷害。如果目標生命低於20%，則額外造成目標最大生命20%的真實傷害。額外造成的傷害最高只能造成自身攻擊的500%', damageMultiplier: 2.5, emoji: '🌪️', maxLevel: 5, specialConditions: [{type: 'execute', executeHpThreshold: 0.2, executeDamageCapMultiplier: 5}], upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 4 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * (l*2) }), upgradeEffect: (l) => ({damageMultiplier: 2.5 + (l-1)*0.3, specialConditions: [{type: 'execute', executeHpThreshold: 0.2 + (l-1)*0.01, executeDamageCapMultiplier: 5 + (l-1)*0.5}]})},
  s019_ssr_dark_support_cooldown: { name: '時光回溯', description: '減少我方全體技能冷卻1回合。', cooldown: 5, emoji: '⏳', maxLevel: 3, cooldownReductionEffect: {amount: 1, targetType: 'all_allies', chance: 1}, upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 3 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * (l+2) }), upgradeEffect: (l) => ({cooldownReductionEffect: {amount: 1 + Math.floor((l-1)/2), targetType: 'all_allies', chance: 1}})},
  s020_ur_dark_aoe_life_steal: { name: '虛無吞噬', description: '對敵方全體造成180%攻擊力的暗屬性傷害，並將造成傷害的30%轉化為自身生命。', damageMultiplier: 1.8, target: 'enemy_all', emoji: '🌌', maxLevel: 5, specialConditions: [{type: 'life_steal', lifeStealPercent: 0.3}], upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 4 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * (l*2) }), upgradeEffect: (l) => ({damageMultiplier: 1.8 + (l-1)*0.22, specialConditions: [{type: 'life_steal', lifeStealPercent: 0.3 + (l-1)*0.05}]})},
  s021_ssr_wind_single_crit_buff: { name: '風之銳襲', description: '對單體敵人造成220%攻擊力的風屬性傷害，並提升自身20%暴擊率，持續2回合。', damageMultiplier: 2.2, cooldown:3, emoji: '🌀', maxLevel: 5, buffs: [{ stat: 'critRate', value: 20, duration: 2, targetType: 'self' }], upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 2.5 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * (l+1) }), upgradeEffect: (l) => ({damageMultiplier: 2.2 + (l-1)*0.25, buffs: [{ stat: 'critRate', value: 20 + (l-1)*5, duration: 2 + Math.floor((l-1)/2), targetType: 'self' }]})},
  s022_n_fire_dot: { name: '小火花', description: '對單體敵人造成70%攻擊力的火屬性傷害，並附加15%的DOT傷害3回合。', damageMultiplier: 0.7, emoji: '🧨', maxLevel: 5, applyStatusEffects: [{type: StatusEffectType.DAMAGE_OVER_TIME, dotDamageMultiplier: 0.15, duration: 3, chance: 1}], upgradeCost: (l) => ({ [Currency.GOLD]: 50*l, [Currency.SKILL_BOOK_NORMAL]: l }), upgradeEffect: (l) => ({damageMultiplier: 0.7 + (l-1)*0.05, applyStatusEffects: [{type: StatusEffectType.DAMAGE_OVER_TIME, dotDamageMultiplier: 0.15 + (l-1)*0.03, duration: 3, chance: 1}]})},
  s023_r_wind_evasion: { name: '幻影步', description: '提升自身20%閃避率，持續2回合。', cooldown: 3, emoji: '🌬️', maxLevel: 3, buffs: [{ stat: 'evasion_increase', value: 20, duration: 2, targetType: 'self' }], upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * l, [Currency.SKILL_BOOK_NORMAL]: SKILL_UPGRADE_COST_BOOK_NORMAL_BASE * l }), upgradeEffect: (l) => ({ buffs: [{ stat: 'evasion_increase', value: 20 + (l-1)*10, duration: 2 + Math.floor((l-1)/2), targetType: 'self' }] })},
  s024_sr_thunder_aoe: { name: '連鎖閃電', description: '對敵方全體造成90%攻擊力的雷屬性傷害。', damageMultiplier: 0.9, target: 'enemy_all', emoji: '🌩️', maxLevel: 5, upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 1.8 * l, [Currency.SKILL_BOOK_NORMAL]: SKILL_UPGRADE_COST_BOOK_NORMAL_BASE * (l+1) }), upgradeEffect: (l) => ({damageMultiplier: 0.9 + (l-1)*0.12})},
  s025_ssr_light_team_buff_atk_def: { name: '聖光祝福', description: '提升我方全體15%攻擊力與防禦力，持續2回合。', cooldown: 4, emoji: '☀️', maxLevel: 4, buffs: [{stat:'attack_increase', value:15, duration:2, targetType:'all_allies'}, {stat:'defense_increase', value:15, duration:2, targetType:'all_allies'}], upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 3 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * (l+2) }), upgradeEffect: (l) => ({buffs: [{stat:'attack_increase', value:15+(l-1)*5, duration:2+Math.floor((l-1)/2), targetType:'all_allies'}, {stat:'defense_increase', value:15+(l-1)*5, duration:2+Math.floor((l-1)/2), targetType:'all_allies'}]})},
  s026_ur_dark_single_instant_kill: { name: '冥界裁決', description: '對單體敵人造成150%攻擊力的暗屬性傷害。若目標生命低於15%，則傷害翻倍。', damageMultiplier: 1.5, cooldown: 5, emoji: '⚖️', maxLevel: 3, specialConditions: [{type: 'if_hp_below_threshold_extra_damage', hpThresholdPercent: 0.15, extraDamageMultiplier: 2}], upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 5 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * (l*2.5) }), upgradeEffect: (l) => ({damageMultiplier: 1.5 + (l-1)*0.2, specialConditions: [{type: 'if_hp_below_threshold_extra_damage', hpThresholdPercent: 0.15 + (l-1)*0.02, extraDamageMultiplier: 2 + (l-1)*0.2}]})},
  s027_water_r_shield_self: { name: '水盾', description: '為自身施加等同攻擊力100%的護盾，持續2回合。', shieldMultiplier: 1.0, target: 'self', cooldown: 3, emoji: '🛡️', maxLevel: 5, upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * l, [Currency.SKILL_BOOK_NORMAL]: SKILL_UPGRADE_COST_BOOK_NORMAL_BASE * l }), upgradeEffect: (l) => ({shieldMultiplier: 1.0 + (l-1)*0.2})},
  // s028_fire_sr_counter removed
  s029_wind_ssr_aoe_spd_debuff: { name: '颶風之縛', description: '對敵方全體造成120%攻擊力的風屬性傷害，並降低目標20%速度，持續2回合。', damageMultiplier: 1.2, target: 'enemy_all', cooldown: 4, emoji: '⛓️', maxLevel: 5, debuffs: [{stat: 'speed_reduction', value: 20, duration: 2, chance: 1, targetType: 'all_enemies'}], upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 2.8 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * (l+1) }), upgradeEffect: (l) => ({damageMultiplier: 1.2 + (l-1)*0.15, debuffs: [{stat: 'speed_reduction', value: 20 + (l-1)*5, duration: 2, chance: 1, targetType: 'all_enemies'}]})},
  s030_thunder_ur_passive_enhance_aoe: { name: '雷神領域', description: '自身存活時，我方全體攻擊力提升15%。(被動)', emoji: '👑', maxLevel: 1, isPassive: true, buffs: [{stat: 'attack_increase', value: 15, duration: 99, targetType: 'all_allies'}], upgradeCost: (l) => ({}), upgradeEffect: (l) => ({})},
  s031_light_n_single_heal: { name: '微光治療', description: '回復我方單體生命值最低角色30%攻擊力的生命。', healMultiplier: 0.3, target: 'ally_single_lowest_hp', cooldown: 2, emoji: '💡', maxLevel: 5, upgradeCost: (l) => ({ [Currency.GOLD]: 80*l, [Currency.SKILL_BOOK_NORMAL]: Math.ceil(l/2) }), upgradeEffect: (l) => ({healMultiplier: 0.3 + (l-1)*0.08})},
  // Skills for Tung Tung Tung Sahur (c_konami)
  s_sahur_strike: { name: 'Sahur Strike', description: '對單體敵人造成1000%攻擊力的光屬性傷害。', damageMultiplier: 10, emoji: '💥🪵', maxLevel: 5, upgradeCost: (l) => ({ [Currency.GOLD]: HIDDEN_HERO_SKILL_COST_GOLD * l, [Currency.SKILL_BOOK_ADVANCED]: HIDDEN_HERO_SKILL_COST_BOOK * l }), upgradeEffect: (l) => ({ damageMultiplier: 10 + (l-1)*2 }) },
  s_tungs_blessing: { name: "Tung's Blessing", description: '戰鬥開始時，我方1回合內100%全屬性提升。(被動)', emoji: '🌟🪵', maxLevel: 1, isPassive: true, buffs: [{stat: 'all_stats', value: 100, duration: 2, targetType: 'all_allies'}], upgradeCost: () => ({}), upgradeEffect: (l) => ({}) },
  s_echoing_woods: { name: 'Echoing Woods', description: '對敵方全體造成300%攻擊力的光屬性傷害，並有25%機率使其無法行動2回合。', damageMultiplier: 3, target: 'enemy_all', cooldown: 4, emoji: '🌳🪵', maxLevel: 3, applyStatusEffects: [{type: StatusEffectType.UNABLE_TO_ACT, chance: 0.25, duration: 2}], upgradeCost: (l) => ({ [Currency.GOLD]: HIDDEN_HERO_SKILL_COST_GOLD * 1.5 * l, [Currency.SKILL_BOOK_ADVANCED]: HIDDEN_HERO_SKILL_COST_BOOK * 1.5 * l }), upgradeEffect: (l) => ({ damageMultiplier: 3 + (l-1)*0.5, applyStatusEffects: [{ type: StatusEffectType.UNABLE_TO_ACT, chance: 0.25 + (l-1)*0.1, duration: 2 }] }) },
  // Skills for Cappuccino Assassino (c_cappuccino)
  s_caffeine_rush: { name: 'Caffeine Rush', description: '我方全體速度提升50%、暴擊率提升30%，持續3回合。', cooldown: 4, emoji: '💨☕', maxLevel: 3, buffs: [{stat: 'speed_increase', value: 50, duration: 3, targetType: 'all_allies'}, {stat: 'critRate', value: 30, duration: 3, targetType: 'all_allies'}], upgradeCost: (l) => ({ [Currency.GOLD]: HIDDEN_HERO_SKILL_COST_GOLD * l, [Currency.SKILL_BOOK_ADVANCED]: HIDDEN_HERO_SKILL_COST_BOOK * l }), upgradeEffect: (l) => ({ buffs: [{stat: 'speed_increase', value: 50 + (l-1)*10, duration: 3 + (l-1), targetType: 'all_allies'}, {stat: 'critRate', value: 30 + (l-1)*5, duration: 3 + (l-1), targetType: 'all_allies'}] }) },
  s_espresso_shot: { name: 'Espresso Shot', description: '對單體敵人造成700%攻擊力的暗屬性傷害，此攻擊無視目標50%防禦力。', damageMultiplier: 7, cooldown: 0, emoji: '☕🎯', maxLevel: 5, specialConditions: [{type: 'ignore_defense', ignoreDefensePercent: 0.5}], upgradeCost: (l) => ({ [Currency.GOLD]: HIDDEN_HERO_SKILL_COST_GOLD * 1.2 * l, [Currency.SKILL_BOOK_ADVANCED]: HIDDEN_HERO_SKILL_COST_BOOK * 1.2 * l }), upgradeEffect: (l) => ({ damageMultiplier: 7 + (l-1)*1.5, specialConditions: [{type: 'ignore_defense', ignoreDefensePercent: 0.5 + (l-1)*0.05}] }) },
  s_shadow_blend: { name: 'Shadow Blend', description: '戰鬥開始時，持續2回合，攻擊力提升100%。(被動)', emoji: '👤☕', maxLevel: 1, isPassive: true, buffs: [{stat: 'attack_increase', value: 100, duration: 2, targetType: 'self'}], upgradeCost: () => ({}), upgradeEffect: (l) => ({}) },
  // Skills for Tralalero Tralala (c_tralala)
  s_oceans_fury: { name: "Ocean's Fury", description: '對敵方全體造成350%攻擊力的水屬性傷害，並吸血傷害的50%', damageMultiplier: 3.5, target: 'enemy_all', cooldown: 3, emoji: '🌊🩸', maxLevel: 5, specialConditions: [{type: 'life_steal', lifeStealPercent: 0.5}], upgradeCost: (l) => ({ [Currency.GOLD]: HIDDEN_HERO_SKILL_COST_GOLD * l, [Currency.SKILL_BOOK_ADVANCED]: HIDDEN_HERO_SKILL_COST_BOOK * l }), upgradeEffect: (l) => ({ damageMultiplier: 3.5 + (l-1)*0.5, specialConditions: [{type: 'life_steal', lifeStealPercent: 0.5 + (l-1)*0.05}] }) },
  s_apex_predator: { name: 'Apex Predator', description: '自身生命值全滿時，回合開始時攻擊力提升75%，持續1回合。(被動)', emoji: '💪🦈', maxLevel: 1, isPassive: true, buffs: [{stat:'attack_increase', value: 75, duration: 1, targetType:'self' /* condition handled in battle logic */ }], upgradeCost: () => ({}), upgradeEffect: (l) => ({}) },
  s_frenzied_bite: { name: 'Frenzied Bite', description: '對單體敵人造成500%攻擊力的水屬性傷害。目標身上每有一個DOT或無法行動，此技能傷害提升20%。', damageMultiplier: 5, emoji: '🦷🎯', maxLevel: 3, specialConditions: [{type: 'damage_boost_per_debuff', damageBoostPerDebuffPercent: 0.2}], upgradeCost: (l) => ({ [Currency.GOLD]: HIDDEN_HERO_SKILL_COST_GOLD * 1.5 * l, [Currency.SKILL_BOOK_ADVANCED]: HIDDEN_HERO_SKILL_COST_BOOK * 1.5 * l }), upgradeEffect: (l) => ({ damageMultiplier: 5 + (l-1)*1, specialConditions: [{type: 'damage_boost_per_debuff', damageBoostPerDebuffPercent: 0.2 + (l-1)*0.05}] }) },
  // Skills for Bombardiro Crocodilo (c_bombardiro)
  s_swamp_terror: { name: 'Swamp Terror', description: '對敵方全體造成400%攻擊力的水屬性傷害，並附加防禦力下降50%效果，持續2回合。', damageMultiplier: 4, target: 'enemy_all', cooldown: 0, emoji: '🐊🌊', maxLevel: 5, debuffs: [{stat: 'defense_reduction', value: 50, duration: 2, chance: 1, targetType: 'all_enemies'}], upgradeCost: (l) => ({ [Currency.GOLD]: HIDDEN_HERO_SKILL_COST_GOLD * l, [Currency.SKILL_BOOK_ADVANCED]: HIDDEN_HERO_SKILL_COST_BOOK * l }), upgradeEffect: (l) => ({ damageMultiplier: 4 + (l-1)*0.6, debuffs: [{stat: 'defense_reduction', value: 50 + (l-1)*5, duration: 2, chance: 1, targetType: 'all_enemies'}] }) },
  s_death_roll: { name: 'Death Roll', description: '對單體敵人造成600%攻擊力的水屬性傷害。若此技能擊殺目標，則立即重置此技能冷卻時間。', damageMultiplier: 6, cooldown: 5, emoji: '🔄🐊', maxLevel: 3, specialConditions: [{type: 'reset_cooldown_on_kill'}], upgradeCost: (l) => ({ [Currency.GOLD]: HIDDEN_HERO_SKILL_COST_GOLD * 1.8 * l, [Currency.SKILL_BOOK_ADVANCED]: HIDDEN_HERO_SKILL_COST_BOOK * 1.8 * l }), upgradeEffect: (l) => ({ damageMultiplier: 6 + (l-1)*1.5 }) },
  s_thick_hide: { name: 'Thick Hide', description: '免疫DOT與無法行動。受到的暴擊傷害降低30%。(被動)', emoji: '🛡️🐊', maxLevel: 1, isPassive: true, buffs: [{stat: 'crit_chance_reduction', value: 30, duration: 99, targetType: 'self' /* Immunity handled in battle logic */ }], upgradeCost: () => ({}), upgradeEffect: (l) => ({}) },
  // Skills for Mo Guan Yu (c_moguanyu)
  s_mgy_demon_slash: { name: '魔神斬', description: '對單體敵人造成280%攻擊力的暗屬性傷害，自身血量高於50%時，額外造成150%傷害。', damageMultiplier: 2.8, emoji: '👹⚔️', cooldown: 3, maxLevel: 5, specialConditions: [{ type: 'if_hp_above_threshold_extra_damage', hpThresholdPercent: 0.5, extraDamageMultiplier: 1.5 }], upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 2.5 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * l }), upgradeEffect: (l) => ({ damageMultiplier: 2.8 + (l-1)*0.3, specialConditions: [{ type: 'if_hp_above_threshold_extra_damage', hpThresholdPercent: 0.5, extraDamageMultiplier: 1.5 + (l-1)*0.2 }] }) },
  s_mgy_crescent_aoe: { name: '青龍偃月', description: '對敵方全體造成150%攻擊力的暗屬性傷害，並降低目標15%防禦力，持續2回合。', damageMultiplier: 1.5, target: 'enemy_all', emoji: '🐉🌙', cooldown: 4, maxLevel: 5, debuffs: [{stat: 'defense_reduction', value: 15, duration: 2, chance: 1, targetType: 'all_enemies'}], upgradeCost: (l) => ({ [Currency.GOLD]: SKILL_UPGRADE_COST_GOLD_BASE * 3 * l, [Currency.SKILL_BOOK_ADVANCED]: SKILL_UPGRADE_COST_BOOK_ADVANCED_BASE * (l > 2 ? l : l-1) }), upgradeEffect: (l) => ({ damageMultiplier: 1.5 + (l-1)*0.2, debuffs: [{stat: 'defense_reduction', value: 15+(l-1)*3, duration: 2, chance: 1, targetType: 'all_enemies'}] }) },
  s_mgy_martial_passive: { name: '武聖之魂', description: '自身攻擊力提升30%，暴擊傷害提升25%。(被動)', emoji: '💪👹', maxLevel: 1, isPassive: true, buffs: [{stat: 'attack_increase', value: 30, duration: 99, targetType: 'self'}, {stat: 'critDmg', value: 25, duration: 99, targetType: 'self'}], upgradeCost: () => ({}), upgradeEffect: (l) => ({}) },

  // World Boss Skills - Agni (Fire Dragon)
  wb_agni_p_aura: { name: '火山靈氣', description: '回合開始時，對全體敵人造成阿格尼攻擊力100%的火屬性真實傷害。阿格尼免疫DOT與無法行動。(被動)', emoji: '🌋', isPassive: true, maxLevel: 1, upgradeCost: () => ({}) },
  wb_agni_p_skin: { name: '熔岩外殼', description: '受到的暴擊傷害降低50%。(被動)', emoji: '🧱', isPassive: true, maxLevel: 1, upgradeCost: () => ({}) },
  wb_agni_a_breath: { name: '煉獄吐息', description: '對全體敵人造成250%攻擊力的火屬性傷害，並施加DOT(每回合30%攻擊力)，持續3回合。', emoji: '🔥💨', target: 'enemy_all', cooldown: 3, damageMultiplier: 2.5, applyStatusEffects: [{type: StatusEffectType.DAMAGE_OVER_TIME, dotDamageMultiplier: 0.3, duration: 3, chance: 1}], maxLevel: 1, upgradeCost: () => ({}) },
  wb_agni_a_eruption: { name: '岩漿噴發', description: '對單體敵人造成400%攻擊力的火屬性傷害，50%機率降低目標30%防禦力，持續2回合。', emoji: '🌋💥', cooldown: 4, damageMultiplier: 4.0, debuffs: [{stat: 'defense_reduction', value: 30, duration: 2, chance: 0.5, targetType: 'enemy_single'}], maxLevel: 1, upgradeCost: () => ({}) },
  wb_agni_a_worldfire: { name: '滅世之火', description: '對全體敵人造成其當前生命20%的傷害(傷害上限為阿格尼攻擊力的5000%)，阿格尼回復造成總傷害50%的生命。', emoji: '☄️🌍', target: 'enemy_all', cooldown: 5, specialConditions: [{type: 'execute', executeHpThreshold: 1.0, executeDamageCapMultiplier: 50 /* Special: executeDamage is % current HP*/}, {type: 'life_steal', lifeStealPercent: 0.5}], maxLevel: 1, upgradeCost: () => ({}) },

  // World Boss Skills - Cocytus (Ice Golem)
  wb_cocytus_p_frostbite: { name: '刺骨嚴寒', description: '回合開始時，所有敵人25%當回合無法行動。(被動)', emoji: '❄️🥶', isPassive: true, maxLevel: 1, upgradeCost: () => ({}), applyStatusEffects: [{type: StatusEffectType.UNABLE_TO_ACT, chance: 0.25, duration: 1}] }, // Note: This needs to be applied to enemies
  wb_cocytus_p_glacial_armor: { name: '冰川護甲', description: '受到的非暴擊傷害降低30%。每次受到攻擊時，有25%機率使攻擊者無法行動1回合。', emoji: '🧊🛡️', isPassive: true, maxLevel: 1, upgradeCost: () => ({}) }, // 'unable to act' on attacker
  wb_cocytus_a_blizzard: { name: '暴風雪', description: '對全體敵人造成200%攻擊力的水屬性傷害，並有40%機率使目標無法行動1回合。', emoji: '🌨️❄️', target: 'enemy_all', cooldown: 3, damageMultiplier: 2.0, applyStatusEffects: [{type: StatusEffectType.UNABLE_TO_ACT, chance: 0.4, duration: 1}], maxLevel: 1, upgradeCost: () => ({}) },
  wb_cocytus_a_ice_prison: { name: '冰牢術', description: '對單體敵人造成350%攻擊力的水屬性傷害，必定使目標無法行動2回合。', emoji: '🧊🔗', cooldown: 4, damageMultiplier: 3.5, applyStatusEffects: [{type: StatusEffectType.UNABLE_TO_ACT, chance: 1.0, duration: 2}], maxLevel: 1, upgradeCost: () => ({}) },
  wb_cocytus_a_absolute_zero: { name: '絕對零度', description: '對全體敵人造成15%最大生命的真實傷害(傷害上限為科賽特斯攻擊力的400%)，並使其攻擊力下降25%，持續2回合。', emoji: '🥶📉', target: 'enemy_all', cooldown: 5, specialConditions: [{type: 'execute', executeHpThreshold: 1.0, executeDamageCapMultiplier: 4 /* Special: executeDamage is % max HP, true damage*/}], debuffs:[{stat:'attack_reduction', value:25, duration:2, targetType:'all_enemies', chance:1}], maxLevel: 1, upgradeCost: () => ({}) },
  
  // World Boss Skills - Typhon (Storm Titan)
  wb_typhon_p_cyclone_shield: { name: '颶風護盾', description: '戰鬥開始時，獲得一個能吸收自身最大生命值20%傷害的護盾。護盾存在時，速度提升30%。(被動)', emoji: '🌪️🛡️', isPassive: true, maxLevel: 1, upgradeCost: () => ({}) },
  wb_typhon_p_eye_of_storm: { name: '風暴之眼', description: '對所有血量低於50%的敵人，攻擊造成200%傷害。(被動)', emoji: '👁️🌪️', isPassive: true, maxLevel: 1, upgradeCost: () => ({}), specialConditions: [{type: 'if_hp_below_threshold_extra_damage', hpThresholdPercent: 0.5, extraDamageMultiplier: 2.0 }]}, // This is now a damage boost
  wb_typhon_a_chain_lightning: { name: '連鎖閃電', description: '對敵方隨機3個目標造成180%攻擊力的風屬性傷害。每次命中時，有30%機率降低目標10%命中，持續2回合。', emoji: '⚡🔗', target: 'random_enemy_targets', numRandomTargets: 3, cooldown: 3, damageMultiplier: 1.8, debuffs: [{stat:'accuracy_perc' as any, value:10, duration:2, chance:0.3, targetType:'enemy_single'}], maxLevel: 1, upgradeCost: () => ({}) },
  wb_typhon_a_gale_force: { name: '風神衝擊', description: '對單體敵人造成450%攻擊力的風屬性傷害，並清除自身所有負面效果。並追加敵人20%最大生命值的傷害。', emoji: '💨⚔️', cooldown: 4, damageMultiplier: 4.5, maxLevel: 1, upgradeCost: () => ({}), specialConditions: [{type: 'execute', executeHpThreshold: 1.0, executeDamageCapMultiplier: 999 /* Cap handled by description text, large number to not interfere with the 20% max HP part */ }] }, // Special condition for % max HP part needs battle logic
  wb_typhon_a_tempest: { name: '天空之怒', description: '對全體敵人造成300%攻擊力的風屬性傷害。此技能暴擊率額外提升20%，暴擊傷害額外提升50%。', emoji: '🌩️🌍', target: 'enemy_all', cooldown: 5, damageMultiplier: 3.0, buffs: [{stat:'critRate', value:20, duration:0, targetType:'self'}, {stat:'critDmg', value:50, duration:0, targetType:'self'}], maxLevel: 1, upgradeCost: () => ({}) },
};

const mapSkills = (skillIds: string[]): BaseSkill[] => {
    return skillIds.map(id => {
      const skillData = BASE_SKILLS_DATA[id];
      if (!skillData) {
        console.error(`Skill definition for ID "${id}" not found in BASE_SKILLS_DATA.`);
        // Return a fallback skill or handle the error as appropriate
        return { 
            id, 
            name: "Unknown Skill", 
            description: "Skill data missing.", 
            emoji: "❓", 
            maxLevel: 1, 
            upgradeCost: () => ({}), 
            isPassive: false,
            target: 'enemy_single',
        } as BaseSkill;
      }
      return { id, ...skillData } as BaseSkill;
    }).filter(Boolean);
}

// Hidden heroes base stats (same as c_konami)
const HIDDEN_HERO_BASE_HP = 66666;
const HIDDEN_HERO_BASE_ATK = 6666;
const HIDDEN_HERO_BASE_DEF = 6666;
const HIDDEN_HERO_BASE_SPD = 6666; // Note: This is extremely high.
const HIDDEN_HERO_CRIT_RATE = 25;
const HIDDEN_HERO_CRIT_DMG = 100;
const HIDDEN_HERO_ACCURACY = 100;
const HIDDEN_HERO_EVASION = 20;

export const BASE_CHARACTERS: Character[] = [
  { id: 'c001', name: '見習水兵', rarity: CharacterRarity.N, element: ElementType.WATER, baseHp: 800, baseAtk: 80, baseDef: 60, baseSpd: 90, critRate: 5, critDmg: 50, accuracy: 95, evasion: 5, spriteEmoji: '👮', skills: mapSkills(['defaultAttack', 's001_water_single']) },
  { id: 'c002', name: '火焰幼犬', rarity: CharacterRarity.R, element: ElementType.FIRE, baseHp: 1200, baseAtk: 120, baseDef: 90, baseSpd: 100, critRate: 5, critDmg: 50, accuracy: 95, evasion: 5, spriteEmoji: '🐕', skills: mapSkills(['defaultAttack', 's003_fire_single']) },
  { id: 'c003', name: '風語者', rarity: CharacterRarity.SR, element: ElementType.WIND, baseHp: 2000, baseAtk: 180, baseDef: 150, baseSpd: 110, critRate: 10, critDmg: 50, accuracy: 95, evasion: 5, spriteEmoji: '🧝', skills: mapSkills(['defaultAttack', 's005_wind_aoe', 's006_wind_buff']) },
  { id: 'c004', name: '雷霆領主', rarity: CharacterRarity.SSR, element: ElementType.THUNDER, baseHp: 3500, baseAtk: 300, baseDef: 250, baseSpd: 120, critRate: 15, critDmg: 60, accuracy: 95, evasion: 10, spriteEmoji: '🦁', skills: mapSkills(['defaultAttack', 's007_thunder_single_stun', 's008_thunder_multi']) },
  { id: 'c005', name: '海洋女皇', rarity: CharacterRarity.UR, element: ElementType.WATER, baseHp: 5000, baseAtk: 450, baseDef: 350, baseSpd: 130, critRate: 20, critDmg: 70, accuracy: 100, evasion: 10, spriteEmoji: '👸', skills: mapSkills(['defaultAttack', 's009_ur_water_aoe_debuff', 's010_ur_water_team_heal_shield']) },
  { id: 'c006', name: '煉獄君王', rarity: CharacterRarity.SSR, element: ElementType.FIRE, baseHp: 3600, baseAtk: 320, baseDef: 240, baseSpd: 115, critRate: 15, critDmg: 65, accuracy: 95, evasion: 10, spriteEmoji: '👹', skills: mapSkills(['defaultAttack', 's011_ssr_fire_aoe_dot', 's012_ssr_fire_passive_buff']) },
  { id: 'c007', name: '聖殿守護者', rarity: CharacterRarity.SR, element: ElementType.LIGHT, baseHp: 2500, baseAtk: 150, baseDef: 200, baseSpd: 95, critRate: 5, critDmg: 50, accuracy: 95, evasion: 5, spriteEmoji: '😇', skills: mapSkills(['defaultAttack', 's013_light_protect']) },
  { id: 'c008', name: '暗影刺客', rarity: CharacterRarity.SSR, element: ElementType.DARK, baseHp: 3000, baseAtk: 350, baseDef: 180, baseSpd: 135, critRate: 20, critDmg: 70, accuracy: 100, evasion: 15, spriteEmoji: '🥷', skills: mapSkills(['defaultAttack', 's014_dark_sacrifice', 's008_thunder_multi']) },
  { id: 'c009', name: '光輝大祭司', rarity: CharacterRarity.UR, element: ElementType.LIGHT, baseHp: 4800, baseAtk: 400, baseDef: 400, baseSpd: 110, critRate: 10, critDmg: 50, accuracy: 100, evasion: 5, spriteEmoji: '🙏', skills: mapSkills(['defaultAttack', 's015_ur_light_revive', 's010_ur_water_team_heal_shield']) }, // s010 is heal all
  { id: 'c010', name: '沙丘之影', rarity: CharacterRarity.SR, element: ElementType.DARK, baseHp: 2200, baseAtk: 200, baseDef: 130, baseSpd: 115, critRate: 10, critDmg: 55, accuracy: 95, evasion: 10, spriteEmoji: '👤', skills: mapSkills(['defaultAttack', 's016_dark_sr_dot']) },
  { id: 'c011', name: '星界漫遊者', rarity: CharacterRarity.SSR, element: ElementType.LIGHT, baseHp: 3700, baseAtk: 280, baseDef: 300, baseSpd: 105, critRate: 15, critDmg: 60, accuracy: 100, evasion: 5, spriteEmoji: '🚶', skills: mapSkills(['defaultAttack', 's017_light_ssr_shield_reflect', 's002_water_heal']) }, // s002 is single heal
  { id: 'c012', name: '風暴女武神', rarity: CharacterRarity.UR, element: ElementType.WIND, baseHp: 4900, baseAtk: 480, baseDef: 320, baseSpd: 135, critRate: 25, critDmg: 75, accuracy: 100, evasion: 15, spriteEmoji: '💃', skills: mapSkills(['defaultAttack', 's018_ur_wind_single_execute', 's005_wind_aoe']) },
  { id: 'c013', name: '虛空編織者', rarity: CharacterRarity.SSR, element: ElementType.DARK, baseHp: 3200, baseAtk: 290, baseDef: 280, baseSpd: 110, critRate: 10, critDmg: 50, accuracy: 100, evasion: 5, spriteEmoji: '🔮', skills: mapSkills(['defaultAttack', 's019_ssr_dark_support_cooldown', 's016_dark_sr_dot']) },
  { id: 'c014', name: '幽影主宰', rarity: CharacterRarity.UR, element: ElementType.DARK, baseHp: 5200, baseAtk: 470, baseDef: 330, baseSpd: 125, critRate: 22, critDmg: 72, accuracy: 100, evasion: 12, spriteEmoji: '😈', skills: mapSkills(['defaultAttack', 's020_ur_dark_aoe_life_steal', 's014_dark_sacrifice']) },
  { id: 'c015', name: '風靈射手', rarity: CharacterRarity.SSR, element: ElementType.WIND, baseHp: 3400, baseAtk: 310, baseDef: 230, baseSpd: 125, critRate: 18, critDmg: 62, accuracy: 98, evasion: 8, spriteEmoji: '🏹', skills: mapSkills(['defaultAttack', 's021_ssr_wind_single_crit_buff', 's005_wind_aoe']) },
  { id: 'c016', name: '火焰哥布林', rarity: CharacterRarity.N, element: ElementType.FIRE, baseHp: 750, baseAtk: 90, baseDef: 50, baseSpd: 95, critRate: 5, critDmg: 50, accuracy: 90, evasion: 5, spriteEmoji: '👺', skills: mapSkills(['defaultAttack', 's022_n_fire_dot']) },
  { id: 'c017', name: '水元素使', rarity: CharacterRarity.R, element: ElementType.WATER, baseHp: 1300, baseAtk: 110, baseDef: 100, baseSpd: 98, critRate: 5, critDmg: 50, accuracy: 95, evasion: 5, spriteEmoji: '💧', skills: mapSkills(['defaultAttack', 's001_water_single', 's027_water_r_shield_self']) },
  { id: 'c018', name: '風行盜賊', rarity: CharacterRarity.R, element: ElementType.WIND, baseHp: 1100, baseAtk: 130, baseDef: 80, baseSpd: 115, critRate: 10, critDmg: 55, accuracy: 95, evasion: 10, spriteEmoji: '🏃', skills: mapSkills(['defaultAttack', 's005_wind_aoe', 's023_r_wind_evasion']) },
  { id: 'c019', name: '雷電法師', rarity: CharacterRarity.SR, element: ElementType.THUNDER, baseHp: 1900, baseAtk: 200, baseDef: 140, baseSpd: 105, critRate: 10, critDmg: 50, accuracy: 95, evasion: 5, spriteEmoji: '🧙', skills: mapSkills(['defaultAttack', 's008_thunder_multi', 's024_sr_thunder_aoe']) },
  { id: 'c020', name: '光輝騎士', rarity: CharacterRarity.SSR, element: ElementType.LIGHT, baseHp: 3800, baseAtk: 290, baseDef: 310, baseSpd: 100, critRate: 10, critDmg: 55, accuracy: 100, evasion: 5, spriteEmoji: '🛡️', skills: mapSkills(['defaultAttack', 's013_light_protect', 's025_ssr_light_team_buff_atk_def']) },
  { id: 'c021', name: '暗夜判官', rarity: CharacterRarity.UR, element: ElementType.DARK, baseHp: 5100, baseAtk: 460, baseDef: 340, baseSpd: 128, critRate: 20, critDmg: 70, accuracy: 100, evasion: 10, spriteEmoji: '⚖️', skills: mapSkills(['defaultAttack', 's026_ur_dark_single_instant_kill', 's016_dark_sr_dot']) },
  { id: 'c022', name: '鐵甲戰士', rarity: CharacterRarity.N, element: ElementType.FIRE, baseHp: 900, baseAtk: 70, baseDef: 80, baseSpd: 80, critRate: 5, critDmg: 50, accuracy: 95, evasion: 0, spriteEmoji: '👨‍🚒', skills: mapSkills(['defaultAttack', 's003_fire_single']) },
  { id: 'c023', name: '火焰術士', rarity: CharacterRarity.SR, element: ElementType.FIRE, baseHp: 2100, baseAtk: 190, baseDef: 140, baseSpd: 108, critRate: 12, critDmg: 55, accuracy: 95, evasion: 5, spriteEmoji: '🔥', skills: mapSkills(['defaultAttack', 's011_ssr_fire_aoe_dot' /* s028 removed */]) },
  { id: 'c024', name: '颶風領主', rarity: CharacterRarity.SSR, element: ElementType.WIND, baseHp: 3550, baseAtk: 305, baseDef: 245, baseSpd: 122, critRate: 16, critDmg: 60, accuracy: 98, evasion: 8, spriteEmoji: '👑', skills: mapSkills(['defaultAttack', 's029_wind_ssr_aoe_spd_debuff', 's005_wind_aoe']) },
  { id: 'c025', name: '雷神化身', rarity: CharacterRarity.UR, element: ElementType.THUNDER, baseHp: 5050, baseAtk: 455, baseDef: 355, baseSpd: 132, critRate: 22, critDmg: 72, accuracy: 100, evasion: 10, spriteEmoji: '⚡', skills: mapSkills(['defaultAttack', 's007_thunder_single_stun', 's030_thunder_ur_passive_enhance_aoe']) },
  { id: 'c026', name: '光明侍僧', rarity: CharacterRarity.N, element: ElementType.LIGHT, baseHp: 850, baseAtk: 60, baseDef: 70, baseSpd: 92, critRate: 5, critDmg: 50, accuracy: 98, evasion: 2, spriteEmoji: '🧑‍⚕️', skills: mapSkills(['defaultAttack', 's031_light_n_single_heal']) },
  // Konami Code Hero (already defined, just ensuring it's here)
  { id: 'c_konami', name: 'Tung Tung Tung Sahur', rarity: CharacterRarity.UR, element: ElementType.LIGHT, baseHp: HIDDEN_HERO_BASE_HP, baseAtk: HIDDEN_HERO_BASE_ATK, baseDef: HIDDEN_HERO_BASE_DEF, baseSpd: HIDDEN_HERO_BASE_SPD, critRate: HIDDEN_HERO_CRIT_RATE, critDmg: HIDDEN_HERO_CRIT_DMG, accuracy: HIDDEN_HERO_ACCURACY, evasion: HIDDEN_HERO_EVASION, spriteEmoji: '🪵', skills: mapSkills(['s_sahur_strike', 's_tungs_blessing', 's_echoing_woods']) },
  // Cappuccino Assassino
  { id: 'c_cappuccino', name: 'Cappuccino Assassino', rarity: CharacterRarity.UR, element: ElementType.DARK, baseHp: HIDDEN_HERO_BASE_HP, baseAtk: HIDDEN_HERO_BASE_ATK, baseDef: HIDDEN_HERO_BASE_DEF, baseSpd: HIDDEN_HERO_BASE_SPD, critRate: HIDDEN_HERO_CRIT_RATE, critDmg: HIDDEN_HERO_CRIT_DMG, accuracy: HIDDEN_HERO_ACCURACY, evasion: HIDDEN_HERO_EVASION, spriteEmoji: '☕', skills: mapSkills(['s_caffeine_rush', 's_espresso_shot', 's_shadow_blend']) },
  // Tralalero Tralala
  { id: 'c_tralala', name: 'Tralalero Tralala', rarity: CharacterRarity.UR, element: ElementType.WATER, baseHp: HIDDEN_HERO_BASE_HP, baseAtk: HIDDEN_HERO_BASE_ATK, baseDef: HIDDEN_HERO_BASE_DEF, baseSpd: HIDDEN_HERO_BASE_SPD, critRate: HIDDEN_HERO_CRIT_RATE, critDmg: HIDDEN_HERO_CRIT_DMG, accuracy: HIDDEN_HERO_ACCURACY, evasion: HIDDEN_HERO_EVASION, spriteEmoji: '🦈', skills: mapSkills(['s_oceans_fury', 's_apex_predator', 's_frenzied_bite']) },
  // Bombardiro Crocodilo
  { id: 'c_bombardiro', name: 'Bombardiro Crocodilo', rarity: CharacterRarity.UR, element: ElementType.WATER, baseHp: HIDDEN_HERO_BASE_HP, baseAtk: HIDDEN_HERO_BASE_ATK, baseDef: HIDDEN_HERO_BASE_DEF, baseSpd: HIDDEN_HERO_BASE_SPD, critRate: HIDDEN_HERO_CRIT_RATE, critDmg: HIDDEN_HERO_CRIT_DMG, accuracy: HIDDEN_HERO_ACCURACY, evasion: HIDDEN_HERO_EVASION, spriteEmoji: '🐊', skills: mapSkills(['s_swamp_terror', 's_death_roll', 's_thick_hide']) },
  // Mo Guan Yu
  { id: 'c_moguanyu', name: '魔關羽', rarity: CharacterRarity.SSR, element: ElementType.DARK, baseHp: 3200, baseAtk: 380, baseDef: 200, baseSpd: 125, critRate: 15, critDmg: 65, accuracy: 100, evasion: 10, spriteEmoji: '👹', skills: mapSkills(['s_mgy_demon_slash', 's_mgy_crescent_aoe', 's_mgy_martial_passive']) },
];

// This list is used for Gacha Pools and general game logic, excluding hidden heroes from appearing in NPC teams or random drops.
export const REGULAR_CHARACTERS: Character[] = BASE_CHARACTERS.filter(
  c => !['c_konami', 'c_cappuccino', 'c_tralala', 'c_bombardiro', 'c_moguanyu'].includes(c.id)
);


export const PLAYER_INITIAL_LEVEL = 1;
export const LEVEL_UP_EXP_COST_BASE = 100;
export const LEVEL_UP_GOLD_COST_BASE = 1000;
